#services:
 # postgres-db:
  #  image: postgres:16-alpine
   # container_name: postgres_report_container
    #environment:
     # POSTGRES_USER: bindhup
      #POSTGRES_PASSWORD: Krishna@26
      #POSTGRES_DB: postgres-db
    #volumes:
     # - pgdata:/var/lib/postgresql/data


  #app-service:
   # build:
    #  context: .
     # dockerfile: Dockerfile
    #container_name: spring_report_container
    #ports:
     # - "8080:8080"
    #depends_on:
    #  postgres-db:
     #   condition: service_healthy
    #environment:
     # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres-db
      #SPRING_DATASOURCE_USERNAME: bindhup
      #SPRING_DATASOURCE_PASSWORD: Krishna@26

#volumes:
 # pgdata: