name: Terraform CD
on:
  workflow_run:
    workflows: ["Report App pipeline"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:


env:
  AWS_REGION: us-east-1

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    container:
      image: docker.io/bindhup/report-app-testing:latest
      credentials:
        username: bindhup
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Terraform init
        run: terraform init -reconfigure

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan

      - name: Force ECS deployment
        run: |
          aws ecs update-service \
            --cluster report-app-test-cluster \
            --service report-app-test \
            --force-new-deployment

      - name: Print application URL
        run: terraform output application_url
